const emoticons = {
    "tick": "✔",
    "cross": "✘",
    "box_tick": "☑",
    "box_cross": "☒",
    "heart": "❤",
    "star": "★",
    "smile": "☺",
    "sun": "☀",
    "bear_neutral": "ʕ·ᴥ·ʔ",
    "bear_hug": "ʕっ·ᴥ·ʔっ",
    "bear_love": "ʕ♥ᴥ♥ʔ",
    "bird_face": "(°v°)",
    "cat_face": "(°ᴥ°)",
    "dog_face": "(◕ᴥ◕ʋ)",
    "face_cheer1": "※\\(^o^)/※",
    "face_cheer2": "*(^_^)*",
    "face_cool1": "(⌐■_■)",
    "face_cool2": "(•_•) ( •_•)>⌐■-■ (⌐■_■)",
    "face_creep": "ԅ(≖‿≖ԅ)",
    "face_cry": "(╥﹏╥)",
    "face_shrug": "¯\\_(ツ)_/¯",
    "face_shrug_confused": "¯\\(°_o)/¯",
    "face_gimme": "༼ つ◕_◕༽つ",
    "face_lol": "L(°O°L)",
    "face_zoidberg": "(V)(°,,,°)(V)",
    "face_fly": "─=≡Σ((つ•ω•)つ",
    "face_surprised": "(°_°)",
    "face_sleep": "(-_-) zzZ",
    "face_wide_eyed":"(O_O)",
    "face_skeptical": "(ㆆ_ㆆ)",
    "face_worry": "(●´⌓`●)",
    "face_cute_smile": "(｡◕‿‿◕｡)",
    "face_disapproval": "(ಠ_ಠ)",
    "face_sly_smile": "(-‿-)",
    "face_happy_1": "(◠‿◠)",
    "face_happy_2": "(•‿•)",
    "face_happy_3": "(◕‿◕)",
    "face_happy_4": " (＾▽＾)",
    "face_flower_smile": "(✿◠‿◠)",
    "face_confused": "(°o•)",
    "face_table_flip": "(╯°□°）╯︵ ┻━┻"
}
export default emoticons;